### ISSUE TITLE
Bug in Academic Personnel Section, after changing Department to 'Educational & Social Policy' from 'Music Science & Art'

### ISSUE THREAD

**Issue by GDGouravDey** [open-source-uom/myuom#54]
In the Academic Personnel Page, a bug is encountered whenever I change the Department from 'Music Science & Art' to 'Educational & Social Policy'. Two new cards for professors is rendered, which do not expand on click. Also, on further changing to other departments, the two extra cards keep showing on other pages too.

Bug Image :- 

![Screenshot 2024-03-07 014614](https://github.com/open-source-uom/myuom/assets/117531461/0b5bb62c-1d9f-4da4-b815-207a89757315)

Video showing Bug :-

https://github.com/open-source-uom/myuom/assets/117531461/a721b331-581d-4034-8ab8-6ccc56a4b11f

**Comment by sankalpie** [comment]
This issue is occurring because 3 academic personnel have the same telephone number. So, this is interfering with the "unique key" requirement of mapping over the filteredArray

Currently it is an easy fix! 
We have 2 options:
* The telephone numbers of personnel need to be changed in the data->Music.js (if preferred static rendering)
* Or we can use array index as key
